 - name: Install dependencies for Debian-based systems
   when: ansible_os_family == "Debian"
   apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
   with_items:
        - openjdk-11-jdk
        - unzip  

 - name: Install dependencies for Red Hat-based systems
   when: ansible_os_family == "RedHat"
   yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
   with_items:
        - java-11-openjdk-devel
        - unzip