---
- name: Creating a user for opensearch
  tasks:
    - include_tasks: user_opensrch.yml

- name: Making directory for opensearch
  tasks:
    - include_tasks: opensrch_dir.yml

- name: Install dependencies for opensearch
  tasks:
    - include_tasks: dependecies_opensrch.yml

- name: Download opensearch
  tasks:
    - include_tasks: downloadopensearch.yml

- name: Extracting opensearch
  tasks:
    - include_tasks: extracting.yml

# Uncomment the following section if required
# - name: Installing opensearch
#   hosts: all
#   tasks:
#     - include_tasks: install_os.yml

- name: Configuring opensearch
  tasks:
    - include_tasks: configure_opensrch.yml

- name: Install dashboard
  tasks:
    - include_tasks: dashboard.yml
